---
title: "CDC Data"
author: "Isaac Johnson and Jesse Debolt"
date: "2023-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Read in Data
```{r}
library(tidyverse)
library(skimr)
library(DataExplorer)
library(GGally)

prevalence_chd <- read.csv("/Volumes/Files/datasets/prevalence_chd.csv")
prevalence_hbp <- read.csv("/Volumes/Files/datasets/prevalence_hbp.csv")
prevalence_stroke <- read.csv("/Volumes/Files/datasets/prevalence_stroke.csv")
hospitals <- read.csv("/Volumes/Files/datasets/hospitals.csv")
hospitals_cic <- read.csv("/Volumes/Files/datasets/hospitals_cic.csv")
hospitals_cr <- read.csv("/Volumes/Files/datasets/hospitals_cr.csv")
pcp <- read.csv("/Volumes/Files/datasets/pcp.csv")
cvdr <- read.csv("/Volumes/Files/datasets/cvdr.csv")
pharmacies <- read.csv("/Volumes/Files/datasets/pharmacies.csv")
insured <- read.csv("/Volumes/Files/datasets/insured.csv")
rural_urban <- read.csv("/Volumes/Files/datasets/rural_urban.csv")
broadband <- read.csv("/Volumes/Files/datasets/broadband.csv")
computer <- read.csv("/Volumes/Files/datasets/computer.csv")

```

##Rename columns and drop columns
```{r}

prevalence_chd <- rename(prevalence_chd, prevalence_chd = Value) %>%
    select(-theme_range)
prevalence_hbp <- rename(prevalence_hbp, prevalence_hbp = Value) %>%
    select(-theme_range)
prevalence_stroke <- rename(prevalence_stroke, prevalence_stroke = Value) %>%
    select(-theme_range)
hospitals <- rename(hospitals, hospitals = Value) %>%
    select(-theme_range)
hospitals_cic <- rename(hospitals_cic, hospitals_cic = Value) %>%
    select(-theme_range)
hospitals_cr <- rename(hospitals_cr, hospitals_cr = Value) %>%
    select(-theme_range)
pcp <- rename(pcp, pcp = Value) %>%
    select(-theme_range)
cvdr <- rename(cvdr, cvdr = Value) %>%
    select(-theme_range)
pharmacies <- rename(pharmacies, pharmacies = Value) %>%
    select(-theme_range)
insured <- rename(insured, insured = Value) %>%
    select(-theme_range)
rural_urban <- rename(rural_urban, rural_urban_value = Value)
rural_urban <- rename(rural_urban,rural_urban_size = theme_range)
broadband <- rename(broadband, broadband = Value) %>%
    select(-theme_range)
computer <- rename(computer, computer = Value) %>%
    select(-theme_range)

```


##Join datasets
```{r}

cdc <- prevalence_chd %>%
    full_join(prevalence_hbp, by = c("cnty_fips", "display_name")) %>%
    full_join(prevalence_stroke, by = c("cnty_fips", "display_name")) %>%
    full_join(hospitals, by = c("cnty_fips", "display_name")) %>%
    full_join(hospitals_cic, by = c("cnty_fips", "display_name")) %>%
    full_join(hospitals_cr, by = c("cnty_fips", "display_name")) %>%
    full_join(pcp, by = c("cnty_fips", "display_name")) %>%
    full_join(cvdr, by = c("cnty_fips", "display_name")) %>%
    full_join(pharmacies, by = c("cnty_fips", "display_name")) %>%
    full_join(insured, by = c("cnty_fips", "display_name")) %>%
    full_join(rural_urban, by = c("cnty_fips", "display_name")) %>%
    full_join(broadband, by = c("cnty_fips", "display_name")) %>%
    full_join(computer, by = c("cnty_fips", "display_name"))

cdc <- rename(cdc, county = display_name)

```

##Export Dataset
```{r}

write.csv(cdc, "/Users/isaacjohnson/Documents/Scanner Output/School/Willamette/Capstone/Capstone Project/cdc.csv")
```

##EDA (initial look)
```{r}
head(cdc)
str(cdc)
dim(cdc)
summary(cdc)
skim(cdc)
```
##Any missing values?
```{r}

#total number of missing values in each column
colSums(is.na(cdc))

#total number of missing values in dataset
sum(is.na(cdc))

```


##EDA (rural values?)
```{r}

names(cdc)
unique(cdc$rural_urban_value)
rural_query <- filter(cdc, rural_urban_value == -1)
head(rural_query, n=20)
#should we drop the -1 values, they are technically. not US counties, but territories of US etc...VERIFY
```
##EDA - Let's pook at CHD prevalence
```{r}
hist(cdc$prevalence_chd)

#Why are some prevalence values -1? Let's look at them. Maybe it's a non-reporting issue?
sort(unique(cdc$prevalence_chd))
chd_query <- filter(cdc, prevalence_chd == -1)
head(chd_query, n=20)

top_10 <- top_n(cdc, n=10, prevalence_chd)
top_10

bottom_10 <- cdc %>%
    arrange(prevalence_chd) %>%
    tail(10)

```

##EDA 10 Counties with highest CHD prevalence
```{r}

highest_10 <- top_n(cdc, n=10, prevalence_chd)
highest_10 %>%
    arrange(desc(prevalence_chd))

```
##EDA 10 Counties with lowest CHD prevalence
```{r}

lowest_10 <- cdc %>%
    filter(prevalence_chd != -1) %>%
    arrange(prevalence_chd) %>%
    head(10)
lowest_10

```

##EDA Correlation
```{r}

plot_correlation(cdc)

```


##EDA (auto EDA report)
```{r}

cdc %>%
    create_report(
        output_file = paste ("Report", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), sep=" - "),
        report_title = "EDA Report - CHD Dataset",
        y = "cardio"
    )

```

##EDA GGally
```{r}

cdc %>%
    select(prevalence_chd, prevalence_hbp, prevalence_stroke, rural_urban_value) %>%
    ggpairs(mapping = aes(color = cdc$rural_urban_size, alpha = 0.5))

```



